name: omnifex-server

services:
  valkey:
    image: valkey/valkey:9-alpine
    ports:
      - "6379:6379"
    volumes:
      - omnifex-valkey-data:/data
    healthcheck:
      test: [ "CMD-SHELL", "valkey-cli ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    volumes:
      - omnifex-minio-data:/data
    healthcheck:
      test: [ "CMD-SHELL", "mc ready local" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  omnifex-valkey-data:
  omnifex-minio-data:
