name: omnifex-db

services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: omnifex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - omnifex-postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d omnifex" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  omnifex-postgresql-data:
