name: Deploy

on:
  push:
    branches: ['master']

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx API
        uses: docker/setup-buildx-action@v3
        id: buildxAPI

      - name: Set up Docker Buildx Web
        uses: docker/setup-buildx-action@v3
        id: buildxWeb

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildxAPI.outputs.name }}
          target: api_serve
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}-api:latest

      - name: Build and push Web
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildxWeb.outputs.name }}
          target: web_serve
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}-web:latest

  deploy:
    needs: build-and-push-images
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Coolify
        run: |
          curl -H 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}' ${{ secrets.COOLIFY_WEBHOOK }}
